services:
  mydjango:
    # build: .
    image: regina-django
    container_name: mydjango
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
