services:
  mydjango:
    # build: .
    image: regina-django-supervisor
    container_name: mydjango
    volumes:
      - .:/app
      - ./volume/log:/var/log
    ports:
      - "8000:8000"
      - "8889:8889"
    networks:
      - web

  redis:
    image: redis:4.0-alpine
    container_name: myredis
    ports:
      - "6380:6379"
    networks:
      - web

networks:
  web:
    driver: bridge


# 訪問 Django http://localhost:8000/admin
# 訪問 Supervisor http://localhost:8889/
# docker-compose -f docker-compose-simple.yaml up -d