# 可以一個容器內執行多的進程

services:
  mydjango:
    # build: .
    image: regina-django-supervisor
    container_name: mydjango
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8889:8889"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`localhost`)"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
    networks:
      - web

  redis:
    image: redis:4.0-alpine
    container_name: myredis
    ports:
      - "6380:6379"
    networks:
      - web

  traefik:
    image: traefik:v2.4
    container_name: mytraefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      # - "80:80"
      - "8080:8080"  # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

networks:
  web:
    driver: bridge

# 訪問 Django http://localhost:8000/admin
# 訪問 Swagger http://localhost:8000/swagger/
# 訪問 Traefik Dashboard http://localhost:8080.
# docker-compose -f docker-compose-supervisor.yml up -d
  
  
